- hosts: hummingboard
  vars:
    - dev_install: False
    - nfs_mount: True
  # - hd_mount: True 
  roles:
    - setup
    - role: audio
      audio_card: 'None'
    - mopidy
    - docker-compose
    - role: dev_env
      when: dev_install
