- hosts: odroid
  vars:
    - dev_install: True
  roles:
    - setup
    - role: audio
  #    audio_card: 'hifishield2'
      audio_card: 'hifishieldplus'
    - mopidy
    - role: docker-compose
    - role: dev_env
      when: dev_install
