- hosts: odroid
  vars:
    - dev_install: True
    - nfs_mount: True
  # - hd_mount: True  
  roles:
    - setup
    - role: audio
      audio_card: 'hifishield2'
    - mopidy
    - role: docker-compose
    - role: dev_env
      when: dev_install
