- hosts: raspian
  vars:
    - dev_install: False
    - nfs_mount: True
  # - hd_mount: True
  roles:
    - setup
    - role: audio
      audio_card: 'cirrus'
    - mopidy
    - role: docker-compose
      docker_group_users:
        - pi
    - role: dev_env
      when: dev_install
