---
# defaults file for utils
extra_utils:
  - tmux
  #- mplayer
  - python-pip
  - ncmpcpp
  - mpc
  - python-openssl
  - libffi-dev
alias_functions:
  - d-enter() { docker exec -it "$1" /bin/bash; }
  - d-log() { docker logs "$1"; }
  - alias dmop="docker exec -it mopidy"
  - alias dlog="docker logs --tail=500 mopidy"
  - alias bbb="docker exec -it mopidy /bin/bash"
  - alias beet="docker exec -it mopidy beet"
