---
# tasks file for docker
- name: Test if docker is installed
  command: docker
  register: result
  ignore_errors: True

- name: Download docker install script
  get_url:
    url: https://get.docker.com
    dest: /tmp/docker-install.sh
    mode: "a+x"
  when: result|failed


- name: Run install script
  become: yes
  shell: /bin/sh /tmp/docker-install.sh
  when: result|failed

- name: Remove temporary file
  file:
    path: /tmp/docker-install.sh
    state: absent

- name: Add docker_group_users to the docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  become: yes
  with_items: "{{ ansible_user }}"
  when: ansible_user != 'root'

- name: Set Docker to auto-start
  become: yes
  service: name=docker enabled=true state=started

- name: Install docker-compose
  become: yes
  shell: pip install docker-compose


## Copy Docker-compose.yml
- name: Write Docker Compose
  template:
    src: docker-compose_yml.j2
    dest: ~/docker-compose.yml

# Broken in ansible
# - name: start docker container
#   docker_service:
#     project_src: ~/
#     project_name: music_server
#     state: present

- name: Start container
  shell: "docker-compose up -d"
