---
- name: create mopidy config dir
  file:
    path: ~/.config/mopidy
    state: directory
    mode: 0755

- name: Write Config
  template:
    src: mopidy_conf.j2
    dest: ~/.config/mopidy/mopidy.conf


- name: create beets config dir
  file:
    path: ~/.config/beets
    state: directory
    mode: 0755


- name: Create host entry
  become: yes
  lineinfile:
    path: /etc/hosts
    line: "192.168.1.4 diskstation"
    state: present

- name: Restart service autofs
  become: yes
  service:
    name: autofs
    state: restarted

