---
- name: create mopidy config dir
  file:
    path: ~/.config/mopidy
    state: directory
    mode: 0755

- name: Write Config
  template:
    src: mopidy_conf.j2
    dest: ~/.config/mopidy/mopidy.conf

- name: create data dir
  file:
    path: /data
    state: directory
    mode: 0755

- name: create beets config dir
  file:
    path: ~/.config/beets
    state: directory
    mode: 0755

- name: create net dir
  become: yes
  file:
    path: /net
    state: directory
    mode: 0755

- name: Restart service autofs
  become: yes
  service:
    name: autofs
    state: restarted

- name: setup data dir
  become: yes
  file:
    src: /net/diskstation/volume1/music_store
    dest: /data/music
    state: link

# fdisk entry
# LABEL=EXT_MUSIC /data/music     vfat   defaults,rw,owner,flush,umask=000 0 0



# ln -s /data/music/music_var/beet-config/config.yaml .
