- name: set locale en_US.UTF-8
  locale_gen:
    name: en_US.UTF-8
    state: present
  become: yes

- name: set pi password
  become: yes
  user:
    name: pi
    update_password: always
    password: "{{ lookup('password', 'credentials/root/password length=15') }}"
    groups: audio
    append: yes

- name: set root password
  become: yes
  user:
    name: root
    update_password: always
    password: "{{ lookup('password', 'credentials/root/password length=15') }}"

- name: Install Packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ tools }}"

- name: Create alias functions
  lineinfile:
    path: ~/.bashrc
    line: "{{ item }}"
    state: present
  with_items: "{{ alias_functions }}"

- name: nfs config
  become: yes
  lineinfile:
    path: /etc/auto.master
    regexp: '^#/net'
    line: '/net    -host'
