- name: set locale en_US.UTF-8
  locale_gen:
    name: en_US.UTF-8
    state: present
  become: yes

- name: set user password
  become: yes
  user:
    name: {{ ansible_user }}
    update_password: always
    password: "{{ lookup('password', 'credentials/{{ ansible_user }}/password length=15') }}"
    groups: audio
    append: yes
  when: ansible_user != 'root'

- name: set root password
  become: yes
  user:
    name: root
    update_password: always
    password: "{{ lookup('password', 'credentials/root/password length=15') }}"

- name: Install Packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ tools }}"

- name: Create alias functions
  lineinfile:
    path: ~/.bashrc
    line: "{{ item }}"
    state: present
  with_items: "{{ alias_functions }}"

- name: nfs config
  become: yes
  lineinfile:
    path: /etc/auto.master
    line: '/data   /etc/auto.data'
    state: present
  when: nfs_mount

- name: nfs config data
  become: yes
  lineinfile:
    path: /etc/auto.data
    line: "music   {{ lookup('env','NFS_MOUNT') }}"
    state: present
  when: nfs_mount

# fdisk entry
# LABEL=EXT_MUSIC /data/music     vfat   defaults,rw,owner,flush,umask=000 0 0
- name: Mount up device {{ lookup('env','HD_LABEL') }}
  mount:
    path: /data/music
    src: LABEL={{ lookup('env','HD_LABEL') }}
    fstype: vfat
    state: present
  when: hd_mount
