smb_passwd: False
dev_tools:
    - nfs-kernel-server
    - build-essential
          #- portaudio19-dev
    - git
    - samba
    - samba-common-bin
    - python-glade2
    - mp3val
    - flac
          #- autoconf
          #- automake
          #- libtool
          #- intltool
          #- autopoint
          #- libasound2-dev
          #- libpulse-dev
          #- libmad0-dev
          #- libwavpack-dev
          #- libsndfile1-dev
          #- libcdio-dev
          #- libcddb2-dev
          #- libtool
          #- libsamplerate0-dev
          #- libgtk2.0-dev
          #- libavformat-dev
          #- libcurl4-gnutls-dev
          #- libdbus-1-dev
          #- libfaad-dev
          #- libimlib2-dev
          #- libzip-dev
