---
# tasks file for dev_env
- user:
    name: tom
    comment: "nfs user"
    uid: 501
    shell: /bin/bash
    group: users
    groups: audio
    state: present

- user:
    name: pi
    remove: yes
    state: absent

- name: sudo for tom
  lineinfile:
    path: /etc/sudoers
    line: 'tom   ALL=(ALL) NOPASSWD:ALL'
    regexp: '^tom'
    create: yes
    state: present

- name: create ssh dir
  file:
    path: /home/tom/.ssh
    state: directory
    owner: tom
    group: users
    mode: 0700

- name: create ssh authorization
  copy:
    src: ~/.ssh/id_rsa.pub
    dest: /home/tom/.ssh/authorized_keys
    owner: tom
    group: users
    mode: 0700


- name: create data dir
  file:
    path: /data/music
    state: directory
    mode: 0755

- name: Mount up device EXT_MUSIC
  mount:
    path: /data/music
    src: LABEL=EXT_MUSIC
    fstype: vfat
    state: present

- name: Install Dev Packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ dev_tools }}"

- name: Write SMB Conf
  template:
    src: smb_conf.j2
    dest: /etc/samba/smb.conf

- name: set smb_passwd
  command: (echo {{ smb_passwd }}; echo {{ smb_passwd }}) |  smbpasswd -s -a tom
  register: smb_passwd
