---

# - name: Mount up device EXT_MUSIC
#   mount:
#     path: /data/music
#     src: LABEL=EXT_MUSIC
#     fstype: vfat
#     state: present

- name: Install Dev Packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ dev_tools }}"

- name: Write SMB Conf
  template:
    src: smb_conf.j2
    dest: /etc/samba/smb.conf

- name: set smb_passwd
  become: yes
  command: (echo {{ lookup('password', 'credentials/{{ ansible_user }}/password length=15') }}; echo {{ lookup('password', 'credentials/{{ ansible_user }}/password length=15') }}) |  smbpasswd -s -a {{ ansible_user }}
  register: smb_passwd
  when: ansible_user != 'root'

# - name: set smb_passwd
#   command: "(echo {{ lookup('password', 'credentials/root/password length=15') }} ; echo {{ lookup('password', 'credentials/root/password length=15') }}) |  smbpasswd -s -a"
#   register: smb_passwd
#   when: ansible_user == 'root'

- name: checkout bigbeet
  git:
    repo: 'https://github.com/rawdlite/mopidy-bigbeet.git'
    dest: ~/projects/audio/mopidy-bigbeet

- name: checkout beetslocal
  git:
    repo: 'https://github.com/rawdlite/mopidy-beets-local.git'
    dest: ~/projects/audio/mopidy_proj/mopidy-beetslocal

- name: register bigbeet
  command: docker exec -i mopidy pip install --editable /root/src/mopidy-bigbeet
  register: bigbeet

- name: link beet config
  file:
    src: "~/projects/audio/mopidy-bigbeet/mopidy_bigbeet/schema/config.yaml"
    dest: "~/.config/beets/config.yaml"
    state: link
